### ISSUE TITLE
Support defaulting collections to empty

### ISSUE THREAD

**Issue by vibin** [rharter/auto-value-moshi#100]
Hi, while trying to migrate from Gson to Moshi, and auto-value-gson to auto-value-moshi, I realised that support for defaulting collections to empty is missing (see https://github.com/rharter/auto-value-gson#compiler-options). 

Thanks for the library!

**Comment by vibin** [comment]
I could write a Moshi json adapter which takes in json with explicit `null` values and turn them into `emptyList()`s, but I couldn't handle the case where there's no field in the json at all (because my adapter doesn't even get called). 😞

**Comment by rharter** [comment]
This is something that was included in Gson for historical reasons, but likely won't get included here.  This isn't an issue with the adapter, it's an issue with the JSON.  `null`, empty and missing are different, and can't always be assumed to be the same.

The ideal solution would be to fix your JSON so that it returns valid values.

If you want to work around this on device, you can do so in your value object by hiding the deserialized value in a package private property and exposing something that fits your needs publicly.

```java
@AutoValue public abstract class Foo {
  private List<Bar> bars;

  @Json(name = "bars") @Nullable abstract List<Bar> internalBars();
  public List<Bar> bars() {
    if (bars == null) {
      List<Bar> val = internalBars();
      bars = val != null ? val : Collections.emptyList();
    }
    return bars;
  }
}
```

**Comment by vibin** [comment]
Makes sense, thank you!
