### ISSUE TITLE
When defining an abstract class with generics, compilation fails.

### ISSUE THREAD

**Issue by ErikHellman** [rharter/auto-value-moshi#17]
Given the class `@AutoValue abstract class Foo<T>`, compilation fails when I include auto-value-moshi (`apt 'com.ryanharter.auto.value:auto-value-moshi:0.2-SNAPSHOT'`).

**Comment by AngusMorton** [comment]
Looks like the moshi extension generates the class without generic type parameters.

Given an AutoValue class:

``` java
@AutoValue
public abstract class Action<T> {
  public abstract T value();
}
```

The Moshi extension generates a class with the generic type parameters missing, `final class AutoValue_Action extends $AutoValue_Action` instead of `final class AutoValue_Action<T> extends $AutoValue_Action<T>`

**Comment by ZacSweers** [comment]
@rharter any thoughts on how to go about this? Happy to take a crack at it if you have any ideas around it

**Comment by Meisolsson** [comment]
@rharter Any news on this?

**Comment by dotgc** [comment]
Does this work when T itself is an AutoValue class? For me, it raises a  "java.lang.IllegalArgumentException: Cannot serialize abstract class.." exception.
