### ISSUE TITLE
Cannot find adapter for qualified value in an interface.

### ISSUE THREAD

**Issue by kamikat** [rharter/auto-value-moshi#32]
Using `auto-value-moshi:0.2.2`.

Generated code have problem with `@JsonQualifier` annotation in classes inherited.

``` java
public interface MixinA {
    @HexColor int color();
}

@AutoValue
public abstract class B implements MixinA {

}
```

Using generated `JsonAdapter` will result in

```
java.lang.RuntimeException: No method named color()
```

**Comment by rharter** [comment]
Does this code work if you remove the `@HexColor` annotation?

**Comment by kamikat** [comment]
Yes, the code work without a `@HexColor` annotation.

**Comment by ansman** [comment]
Got this too.

**Comment by luciofm** [comment]
The same happens when using `extends` from a base abstract class...

```
public abstract class BaseModel {
    public abstract @ForSomething Long something();
}
```
```
@AutoValue
public abstract class Model extends BaseModel {
    public abstract String string();
}
```
Will fail with `java.lang.NoSuchMethodException: com.luciofm.test.Model.something()`

this happens because the generated `private JsonAdapter adapter(Moshi moshi, String methodName)` method uses `getDeclaredMethod(methodName)` that don't return inherited methods...

The simple solution would be to use `getMethod(methodName)`...

I'll implement it and send a PR later today
